// Code generated by "stringer -type=ErrCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[InternalServer - -1]
	_ = x[InvalidParam - -2]
	_ = x[Unauthorized - -3]
}

const _ErrCode_name = "未授权参数无效unknown errorok"

var _ErrCode_index = [...]uint8{0, 9, 21, 34, 36}

func (i ErrCode) String() string {
	i -= -3
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+-3), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
